---
- name: Install Docker on worker nodes
  hosts: workers
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Reinstall containerd
      apt:
        name: containerd
        state: present
        force: yes
      notify:
        - restart containerd

  handlers:
    - name: restart containerd
      systemd:
        name: containerd
        state: restarted
=======
          
    - name: Reinstall containerd
      apt:
        name: containerd
        state: present
        force: yes
>>>>>>> a31afd0 (Add task to reinstall containerd)
